name: Trigger auto deployment for container-app-omu2ikzlexsym

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-omu2ikzlexsym-AutoDeployTrigger-b0ea3930-51ca-4cff-9aa0-f08db362a3a2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOMU2IKZLEXSYM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOMU2IKZLEXSYM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOMU2IKZLEXSYM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOMU2IKZLEXSYM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOMU2IKZLEXSYM_REGISTRY_PASSWORD }}
          containerAppName: container-app-omu2ikzlexsym
          resourceGroup: todonodejspgsqlgoogleauth96ac8830
          imageToBuild: default/container-app-omu2ikzlexsym:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


